### ISSUE TITLE
Alpha Build Known Issues Checklist

### ISSUE THREAD

**Issue by RROUOL** [CMP2804M-TSE-Group-28/supernova#18]
NOTE BEFORE YOU DO ANY OF THIS - only one user should be in ANY given scene before pushing, otherwise there will be conflicts - the person solving the AI and entities issue should use the WorldMap scene and other users should be doing their changes elsewhere in a new scene of their own creation, which can be deleted _after_ everything is merged. 

**If you are not the designated WorldMap.scene developer then do not interact with it in any way. Immediately create a new scene and work in that one before you save or make any changes. #17**

- [x] When firing the pistol, the bullet prefabs fired never destruct. This will cause a memory leak. Add in code to call the equivalent of Destroy(pistolBullet, 1.0f)  when shooting. This way bullets will be properly disposed of.

- [x] When going near a switch (purple cubes in the walls) and trying to press E to interact with it, it will not work due to how player inputs are parsed. Someone who understands the input system should fix this so that OpenDoor() is called upon when pressing E while within the trigger collider of the Switch prefab (this is a transparent 5 unit sphere in each direction. You will get a debug.log notification when you enter it).

- [x] Enemies are flat on the ground instead of upright when hitting play. This should be fixed so that they stand upright and face the player.

- [ ] Enemies do not currently have their "aggression zones"  established. Please add one for each enemy based off the area it's in.

- [x] There is not currently HP for players or enemies and bullets do not deal damage. Create this and a coroutine for the player to respawn at the last green area they entered.

- [x] Same as previous but for explosives 

- [x] Boss 1 (Revenant) and Boss 2 (Pinky) have no AI currently. Revenant should fly around at an altitude the player can still shoot them. Pinky should do a charge every few seconds. Both boss' attacks have the ability to destroy objects with tag "Breakable".

- [x] Killing Boss 1 should unlock the ability to use the rocket launcher.

- [x] Killing Boss 2 should set the switch in its arena to SetActive(true), so the player can interact with it to open the door that leads to the end of the game.

- [x] The end of the game is the glowing white wall. Touching this wall will lead to a new scene saying "GAME OVER" and some sample text. Please ensure this works, as its the win condition.

- [x] Player should be able to switch between firing the pistol and firing the rocket launcher (when both are unlocked). Currently both models render no matter which is equipped, and this should be fixed in WeaponHandler.

- [x] Test effectiveness of rocket launcher to ensure it's fully functional - When fired, the rocket should travel in the direction the player faced for 2 seconds or until it collides with something (whichever is first). Once this prerequisite is met, it generates a second "explosion" object 3 units in diameter. This explosion must then check collision to destroy objects of "Breakable" tag, and deal damage to Players/Enemies within the radius.

**Comment by cooperj** [comment]
- [ ] When the rocket goes off, the pistol cannot be heard.

**Comment by cooperj** [comment]
Okay so we got some glitchy texturing here in the boss level, but as im writing this, im really writing this as a ploy to tell @RROUOL  that ive done the switches :)

https://user-images.githubusercontent.com/28831674/170123809-6135f741-17ac-49b3-81c2-f75f73410c9b.mp4

**Comment by cooperj** [comment]
- [ ] @RROUOL Can you go through and place the `Music Switcher`s where you want the ambient music to change. You need to type the name of the clips that are in the `Music Manager`

*FYI: This was made by @Durp076*

**Comment by cooperj** [comment]
>     * [x]  Theres some places where the player can get pushed outside of the map.

This has been fixed, by having a fail safe to kill the player

**Comment by cooperj** [comment]
Yo! This has been done <3
