### ISSUE TITLE
March/April/May QA Branch Updates

### ISSUE THREAD

**Issue by cooperj** [CMP2804M-TSE-Group-28/supernova#6]
## What's this issue?

This issue is tracking all the problems with the QA branch[^1] at the end of March '22.

## Todo:

- [x] Merge in the level environment - currently being worked on by @RROUOL (#7)
- - [x] Add into that scene:
- - - [x] the Player Controller - *currently being worked on by @mattsilverwood* (#1 #3)
- - - [x] the Camera Controller - *currently being worked on by @mattsilverwood* (#3 #4)
- - - [x] the Weapons System - *currently being worked on by @cooperj*
- - - [x] the AI System - *created by @DerpIzStupid and is ready to be merged in? do comment if that is not the case* (#2 #5)
- [ ] Remove placeholder items from the DevRooms, *probably all of the DevRooms could be scrapped as we would have the "final" level done before this point.*
- [ ] Ensure that the game is in a playable state[^2].
- [ ] Fix Main Menu Linking and Scene Ordering

## Finishing Notes:

Before this can be merged back into main, we need to play test the branch as is.

Once the tasks have all been resolved, a built version will be shared internally.

**NB: If you're looking here and are don't see any work assigned to yourself, make sure to open a PR to the QA branch[^3] for the tasks you have completed from the Notion tracker.**

[^1]: The QA branch is the current staging branch where changes are being made before being merged into `main`.

[^2]: We will sort out a way to mark off when we are happy with it later.

[^3]: When opening a PR you should see an option to change what branch you are merging in to, but feel free to ping me if you need any help.

**Comment by cooperj** [comment]
🎉 @RROUOL has completed the level, that is now ready to be merged in, just need to complete a review of the code and then its into qa 😄

**Comment by cooperj** [comment]
🎉 @DerpIzStupid has completed the AI system and is almost ready to be merged (just needs sanity checking to ensure i've not deleted something after I resolved the merge conflict.

**Comment by cooperj** [comment]
🎉 @cooperj (me) completed the basic weapons system.

**Comment by mattsilverwood** [comment]
Apologies for the wait for the player controller, I've been inundated with high priority work as of late.

**Comment by cooperj** [comment]
Most tasks have been completed. This issue is now irrelevant.

**Comment by cooperj** [comment]
(Tiding up will be done at a later stage)
